apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sitio
  namespace: k8s-web-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitio-web
  template:
    metadata:
      labels:
        app: sitio-web
    spec:
      initContainers:
        - name: clonar-sitio
          image: alpine/git
          command: ["/bin/sh", "-c"]
          args:
            - |
              git clone https://github.com/olgbar/static-website.git /mnt/src &&
              cp -r /mnt/src/* /mnt/html/
          volumeMounts:
            - name: sitio-volumen
              mountPath: /mnt/html
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sitio-volumen
              mountPath: /usr/share/nginx/html
      volumes:
        - name: sitio-volumen
          emptyDir: {}
